on: push
name: Render and Publish v2

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: 
          - de
          - en
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tinytex: true
          
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Cache R packages 
       
        uses: actions/cache@v1 
        with: 
           path: ${{ env.R_LIBS_USER }} 
           key: r-localv1
      - name: install dependencies
        run: |
          R -e 'install.packages(c("rmarkdown","RcppTOML"))'

      - name: Render Website + Slides
        uses: quarto-dev/quarto-actions/render@v2
        env: 
          QUARTO_PROFILE: ${{ matrix.language }}
        with:
          to: pdf
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: consent
          path: consent.pdf
          
