on: push
name: Render and Publish v2

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
          
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
      - name: install dependencies
        run: |
          R -e 'install.packages(c("rmarkdown","RcppTOML"))'

      - name: Render Website + Slides
        uses: quarto-dev/quarto-actions/render@v2
        env: 
          QUARTO_PROFILE: en
        with:
          to: pdf
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: paper
          # This is the output path where Pandoc will write the compiled
          # PDF. Note, this should be the same directory as the input
          # paper.md
          path: consent.pdf
