on: push
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: 
          - de
          # - en
    steps:
      - name: Generate Forms
        uses: maanikmarathe/consentform_gh_action@main
        with:
         language: ${{ matrix.language }}
